on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened]

jobs:
  sample_job_in_ts:
    runs-on: ubuntu-latest
    name: A job to test action in ts
    steps:
      - uses: actions/checkout@v4
      - name: Calculating modified strings
        id: ts_calc_strings
        run: |
          echo "${{ github.sha }}"
          bash .github/calc_modified_strings.sh
      - name: TS Action step
        id: ts_step
        uses: tinder-wenbinchen/sample-action-ts@v0.3.9
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          milliseconds: 10000
      # Use the output from the `ts_step` step
      - name: Get the output time
        run: echo "The time was ${{ steps.ts_step.outputs.comment-id }}"